# The image used to build the Dremio cluster. It is recommended to update the
# version tag to the version that you are using. This will ensure that all
# the pods are using the same version of the software.
image: dremio/dremio-oss:latest
# Check out Dremio documentation for memory and cpu requirements for
# the coordinators and the executors.
# The value of memory should be in MB. CPU is in no of cores.
coordinator:
  memory: 1024
  cpu: 1 
  # This count is for slave coordinators only.
  # The chart will always create one master coordinator - you are
  # not required to have more than one master coordinator.
  count: 0
  web:
    port: 9047
  client:
    port: 31010
  volumeSize: 10Gi
executor:
  memory: 1024
  cpu: 1
  count: 3
  volumeSize: 10Gi
zookeeper:
  memory: 1024
  cpu: 0.5
  count: 1
  volumeSize: 10Gi

# If your Kubernetes cluster does not support LoadBalancer,
# comment out the line below for the helm chart to succeed or add
# the correct serviceType for your cluster.
serviceType: ClusterIP

# If the loadBalancer supports sessionAffinity and
# you have one or more coordinators, enable it
#sessionAffinity: ClientIP

# Enable the following flag if you wish to route traffic through a shared VPC
# for the LoadBalancer's external IP.
# The chart is setup for internal IP support for AKS, EKS, GKE.
# For more information, see https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
#internalLoadBalancer: true

# To use custom storage class, uncomment and provide the value here.
# Otherwise the default storage class configured for your K8S cluster is used.
#storageClass: managed-premium

# For private and protected docker image repository, you should store
# the credentials in a kubernetes secret and provide the secret name here.
# For more information, see https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
#imagePullSecrets: secretname

# Target pods to nodes based on labels set on the nodes.
# For more information, see https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
#nodeSelector:
#  key: value

# Control where uploaded files are stored.
# See https://docs.dremio.com/deployment/distributed-storage.html for more information
dremioVersion: "3.2.0" # Dremio Version 3.2.0 or greater
distStorage:
  # Valid values are local, aws, azure or azureStorage. aws and azure choice requires additional configuration data.
  type: "local"
  aws: #S3 - used for only uploads
    bucketName: "Your_AWS_bucket_name"
    path: "/"
    accessKey: "Your_AWS_Access_Key"
    secret: "Your_AWS_Secret"
  azure: #ADLS v1 - used for only uploads
    datalakeStoreName: "Your_Azure_DataLake_Storage_name"
    path: "/"
    applicationId: "Your_Azure_Application_Id"
    secret: "Your_Azure_Secret"
    oauth2EndPoint: "Azure_OAuth2_Endpoint"
  azureStorage: #AzureStorage v2 - supported in Dremio version 3.2.0+ - used for uploads and accelerator
    accountName: "Azure_storage_v2_account_name"
    accessKey: "Access_key_for_the_storage_account"
    filesystem: "Filesystem_in_storage_account"
    uploadsPath: "Path_for_uploads"
    acceleratorPath: "Path_for_accelerator"
